# Generated by Django 5.2.13 on 2026-07-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
